name: PowerShell

on:
  push:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psm1'

jobs:
  analyze:
    name: Analyze PowerShell Scripts
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer and Pester
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Install-Module -Name Pester -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./ -Recurse -Severity Warning,Error -OutVariable issues
          $issues | ForEach-Object { Write-Host "$($_.RuleName): $($_.Message)" }
          if ($issues.Count -gt 0) {
            Write-Error "PSScriptAnalyzer found issues"
            exit 1
          }

      - name: Run Pester Tests (if available)
        shell: pwsh
        run: |
          if (Test-Path './tests') {
            Invoke-Pester -Path ./tests -CI
          } else {
            Write-Host "No tests found. Skipping Pester."
          }

      - name: Secret Scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2

